<?php
?>
<h4>Grouped Class Search</h4>
<form action="<?php echo $this->getUrl("debug/admin_index/searchGroupedClass", array('_secure' => Mage::app()->getStore()->isCurrentlySecure())) ?>" id="class-search-form">
    <input name="uri" class="input-text required-entry" type="search" size="40" />
    <select name="group" class="input-select required-entry">
        <option>all</option>
        <option>model</option>
        <option>block</option>
        <option>helper</option>
    </select>
    <input type="submit" value="<?php echo $this->__('Search Grouped Class Name') ?>" />
</form>
<p>
Search examples: <em>catalog/product</em>, <em>core/url</em>, etc.
</p>
<div id="class-search-results">
<table>
	<thead>
		<tr>
            <th><?php echo $this->__("#") ?></th>
            <th><?php echo $this->__("Group Type") ?></th>
            <th><?php echo $this->__("Search Results") ?></th>
		</tr>
	</thead>
    <tbody>
	</tbody>
</table>
</div>
